language: node_js
node_js: stable

cache:
  directories:
    - node_modules

env:
  global:
    - GH_REF: https://github.com/duola8789/duola8789.github.io.git

script:
  - npm run deploy

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: true
  committer_from_gh: true
  on:
    branch: master

after_script:
  - cd ./public
  - git init
  - git add .
  - git commit -m 'Update Blog By TravisCI'
  - git push --force --quie "https://$GITHUB_TOKEN@${GH_REF}" master:master
