language: node_js

node_js: stable

cache:
  directories:
    - node_modules

deploy:
  provider: pages
  skip_cleanup: true
  keep_history: true
  github_token: $github_token
  committer_from_gh: true
  repo: https://$github_token@github.com/duola8789/duola8789.github.io.git
  on:
    branch: master

script:
  - hexo clean
  - hexo generate
