language: node_js
node_js:
  - "node"
script:
  - npm run deploy
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: true
  committer_from_gh: true
  on:
    branch: master
