language: node_js

node_js: stable

cache:
  directories:
    - node_modules


deploy:
  provider: pages
  skip_cleanup: true
  keep_history: true
  committer_from_gh: true
  on:
    branch: master

script:
  - hexo clean
  - hexo generate
  - hexo deploy
