language: node_js

node_js:
  - 12

cache:
  directories:
    - node_modules

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GH_TOKEN
  keep_history: true
  committer_from_gh: true
  repo: duola8789/duola8789.github.io
  local_dir: public/
  target_branch: master
  on:
    branch: master

script:
  - hexo clean && hexo generate

notifications:
  email:
    recipients:
      - duola8789@126.com
  slack:
    on_success: never
    on_failure: always
