sudo: false

language: node_js

node_js: stable

cache: npm

branches:
  only:
    - master # build master branch only

script:
  - hexo generate # generate static files

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $github_token
  keep_history: true
  local_dir: public/
  on:
    branch: master

notifications:
  email:
    recipients:
      - duola8789@126.com
  slack:
    on_success: never
    on_failure: always
