language: node_js

node_js: stable

cache:
  directories:
    - node_modules

script:
  - npm run generate
  - npm run ${test}
  - npm run delpoy


deploy:
  provider: pages
  skip_cleanup: true
  github_token: github_token
  keep_history: true
  committer_from_gh: true
  on:
    branch: master
