language: node_js

node_js: stable

cache:
  directories:
    - node_modules

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $github_token
  keep_history: true
  committer_from_gh: true
  local_dir: public/
  target_branch: master
  on:
    branch: master

script:
  - hexo clean
  - hexo generate
