language: node_js

node_js: stable

cache:
  directories:
    - node_modules

before_install:
  - git config --global user.name "zh"
  - git config --global user.email "duola8789@126.com"
  - npm install -g hexo-cli
  - export HEXO_DEPLOYER_REPO=https://$github_token@github.com/duola8789/duola8789.github.io.git

script:
  - npm run deploy
