language: node_js

node_js: stable

cache:
  directories:
    - node_modules

deploy:
  provider: pages
  github_token: $github_token
  committer_from_gh: true
  on:
    branch: master

script:
  - hexo clean
  - hexo generate
